/**
 * LocalManagerDriver.java
 * 
 * generated by France Telecom UPnP Generator
 * 
 */

package com.orange.homenap.localmanager.upnp.drivers;


import java.util.Hashtable;
import com.orange.homenap.localmanager.upnp.devices.*;
import org.osgi.service.upnp.UPnPDevice;

    /**
	* This is the class representing a LocalManagerDriver
	*/
public class LocalManagerDriver {
    public Hashtable devices=new Hashtable();

    public void bindUPnPDevice(UPnPDevice dev) {
        devices.put(dev, new LocalManagerDevice(dev, Activator.bundleContext));
    }

    public void unbindUPnPDevice(UPnPDevice dev) {
    	LocalManagerDevice genDevice = (LocalManagerDevice) devices.remove(dev);
    	genDevice.dispose();
    }
}
