/**
 * GlobalCoordinatorDriver.java
 * 
 * generated by France Telecom UPnP Generator
 * 
 */

package com.orange.homenap.globalcoordinator.upnp.drivers;


import java.util.Hashtable;
import com.orange.homenap.globalcoordinator.upnp.devices.*;
import org.osgi.service.upnp.UPnPDevice;

    /**
	* This is the class representing a GlobalCoordinatorDriver
	*/
public class GlobalCoordinatorDriver {
    public Hashtable devices=new Hashtable();

    public void bindUPnPDevice(UPnPDevice dev) {
        devices.put(dev, new GlobalCoordinatorDevice(dev, Activator.bundleContext));
    }

    public void unbindUPnPDevice(UPnPDevice dev) {
    	GlobalCoordinatorDevice genDevice = (GlobalCoordinatorDevice) devices.remove(dev);
    	genDevice.dispose();
    }
}
