/**
 * GlobalCoordinatorDeviceProperties.java
 * 
 * generated by France Telecom UPnP Generator
 * 
 */

package com.orange.homenap.globalcoordinator.upnp.devices;


import org.osgi.service.upnp.*;
import java.util.Properties;

    /**
	* null
	*/
public class GlobalCoordinatorDeviceProperties {
	public final static String UDN               = "FTRD-MAPS-GlobalCoordinator-UPnPGEN";
	public static final String TYPE              = "urn:schemas-upnp-org:device:GlobalCoordinator:1";
	public static final String MANUFACTURER      = "Orange";
	public static final String MODEL_NAME        = "GlobalCoordinator";
	public static final String FRIENDLY_NAME     = "UPnP Global Coordinator";
	public static final String MANUFACTURER_URL  = "remi.druilhe@orange.com";
	public static final String MODEL_DESCRIPTION = "Global Coordinator";
	public static final String MODEL_NUMBER      = "0.1";
	public static final String MODEL_URL         = "/";
	public static final String SERIAL_NUMBER     = "1234267890";
	public static final String UPC               = "3141592";
	public static final String PRESENTATION_URL               = "null";

	public static Properties createProperties(Properties props) {
		props.put("service.pid", UDN);
		props.put(UPnPDevice.UPNP_EXPORT, "");
		props.put(
		        org.osgi.service
		        	.device.Constants.DEVICE_CATEGORY,
		    	new String[]{UPnPDevice.DEVICE_CATEGORY}
		    );
		props.put(UPnPDevice.UDN, UDN);
		props.put(UPnPDevice.TYPE, GlobalCoordinatorDeviceProperties.TYPE);
		props.put(UPnPDevice.MANUFACTURER, GlobalCoordinatorDeviceProperties.MANUFACTURER);
		props.put(UPnPDevice.MODEL_NAME, GlobalCoordinatorDeviceProperties.MODEL_NAME);
		props.put(UPnPDevice.FRIENDLY_NAME, GlobalCoordinatorDeviceProperties.FRIENDLY_NAME);
		props.put(UPnPDevice.MANUFACTURER_URL, GlobalCoordinatorDeviceProperties.MANUFACTURER_URL);
		props.put(UPnPDevice.MODEL_DESCRIPTION, GlobalCoordinatorDeviceProperties.MODEL_DESCRIPTION);
		props.put(UPnPDevice.MODEL_NUMBER, GlobalCoordinatorDeviceProperties.MODEL_NUMBER);
		props.put(UPnPDevice.MODEL_URL, GlobalCoordinatorDeviceProperties.MODEL_URL);
		props.put(UPnPDevice.SERIAL_NUMBER, GlobalCoordinatorDeviceProperties.SERIAL_NUMBER);
		props.put(UPnPDevice.UPC, GlobalCoordinatorDeviceProperties.UPC);
		props.put(UPnPDevice.PRESENTATION_URL, GlobalCoordinatorDeviceProperties.PRESENTATION_URL);
		return props;
	}
}
