/*--------------------------------------------------------
* Module Name : global-coordinator-upnp
* Version : 0.1-SNAPSHOT
*
* Software Name : HomeNap
* Version : 0.1-SNAPSHOT
*
* Copyright © 28/06/2012 – 28/06/2012 France Télécom
* This software is distributed under the Apache 2.0 license,
* the text of which is available at http://www.apache.org/licenses/LICENSE-2.0.html
* or see the "LICENSE-2.0.txt" file for more details.
*
*--------------------------------------------------------
* File Name   : Activator.java
*
* Created     : 28/06/2012
* Author(s)   : Remi Druilhe
*
* Description :
*
* generated by France Telecom UPnP Generator
*
*--------------------------------------------------------
*/

package com.orange.homenap.globalcoordinator.upnp.drivers;


import org.osgi.framework.BundleActivator;
import org.osgi.framework.BundleContext;

    /**
	* This is the generated Activator used to store the BundleContext.
	*/
public class Activator implements BundleActivator{
   static BundleContext bundleContext = null;

   public void start(BundleContext ctxt) throws Exception {
            bundleContext = ctxt;
   }

   public void stop(BundleContext arg0) throws Exception {

   }
}
