/**
 * LocalManagerIconsProperties.java
 * 
 * generated by France Telecom UPnP Generator
 * 
 */

package com.orange.homenap.localmanager.upnp.devices;


import org.osgi.service.upnp.*;
import com.orange.homenap.localmanager.upnp.holders.*;

    /**
	* null
	*/
public class LocalManagerIconsProperties {
}
