#!/bin/sh

#  Module Name : power-state
#  Version : 0.1-SNAPSHOT
#
#  Software Name : HomeNap
#  Version : 0.1-SNAPSHOT
#
#  Copyright © 28/06/2012 – 28/06/2012 France Télécom
#  This software is distributed under the Apache 2.0 license,
#  the text of which is available at http://www.apache.org/licenses/LICENSE-2.0.html
#  or see the "LICENSE-2.0.txt" file for more details.
#
#  File Name   : device-state
#
#  Created     : 28/06/2012
#  Author(s)   : Remi Druilhe
#
#  Description : This script needs to be copied into /etc/pm/sleep.d

case "$1" in
	hibernate|suspend)
		echo $1 > /tmp/state
		;;
	thaw|resume)
		echo $1 > /tmp/state
		;;
	*)
		;;
esac

exit $?

