/**
 * DeployerService.java
 * 
 * generated by France Telecom UPnP Generator
 * 
 */

package com.orange.homenap.localmanager.upnp.services;


import com.orange.homenap.api.IDeployerService;
import org.osgi.service.upnp.*;
import java.util.Hashtable;
import java.util.HashMap;
import java.util.Map;
import java.util.Dictionary;

import org.osgi.framework.*;
import com.orange.homenap.localmanager.upnp.holders.*;

    /**
	* This is the class representing a DeployerService
	*/
public class DeployerService implements IDeployerService {
	UPnPService service;
	Map map=new HashMap();
	BundleContext context;
	ServiceRegistration registration;
	DeployerServiceSkel skel;
	String deviceId;

	public DeployerService(UPnPService service,String deviceId,BundleContext context) {
		this.context=context;
		this.service=service;
		this.deviceId=deviceId;
	}
	public UPnPService getGenericService() {
		return service;
	}
	/**
	* OSGI Stub for UPnP action Start
	*/
	public void start(java.lang.String bundleUrl, java.lang.String migrationState) throws Exception {
		Dictionary dict = null;
		dict = new Hashtable(2);
		dict.put(new String("BundleUrl"), bundleUrl);
		dict.put(new String("MigrationState"), migrationState);
		Hashtable result=null;
		try {
		result=(Hashtable)service.getAction("Start").invoke(dict);
		}
		catch (NullPointerException ex) {
			throw new UPnPGenException("The action is not availaible on the device: It may be an optional action...");
		}
	}
}
