/**
 * DeployerActionHandler.java
 * 
 * generated by France Telecom UPnP Generator
 * 
 */

package com.orange.homenap.localmanager.upnp.services;


import com.orange.homenap.api.IDeployerService;

import java.util.Dictionary;

/**
	* null
	*/
public class DeployerActionHandler {
	public static Dictionary start_invoke(Dictionary args, IDeployerService service) throws Exception {
		Dictionary resultDict = null;
		java.lang.String value0=null;
		try {
			value0=(java.lang.String)args.get("BundleUrl");
		}
		catch (Exception ex) {
			ex.printStackTrace();
		}
		java.lang.String value1=null;
		try {
			value1=(java.lang.String)args.get("MigrationState");
		}
		catch (Exception ex) {
			ex.printStackTrace();
		}
		service.start(value0,value1);
		return resultDict;
	}

}
