/**
 * DeployerVariableProperties.java
 * 
 * generated by France Telecom UPnP Generator
 * 
 */

package com.orange.homenap.localmanager.upnp.services;


import org.osgi.service.upnp.*;
import com.orange.homenap.localmanager.upnp.holders.*;

    /**
	* This is the class representing a DeployerService
	*/
public class DeployerVariableProperties {
	public static final String ARG_TYPE_BUNDLEURL_NAME = "ARG_TYPE_BundleUrl";
	public static final boolean ARG_TYPE_BUNDLEURL_SENDS_EVENTS     = false;
	public static final Class ARG_TYPE_BUNDLEURL_JAVA_DATA_TYPE     = java.lang.String.class;
	public static final String ARG_TYPE_BUNDLEURL_UPNP_DATA_TYPE    = "string";
	public static final String [] ARG_TYPE_BUNDLEURL_ALLOWED_VALUES = null;
	public static final Object ARG_TYPE_BUNDLEURL_DEFAULT_VALUE     = null;
	public static final Number ARG_TYPE_BUNDLEURL_MINIMUM = null;
	public static final Number ARG_TYPE_BUNDLEURL_MAXIMUM = null;
	public static final Number ARG_TYPE_BUNDLEURL_STEP = null;

	public static final String ARG_TYPE_MIGRATIONSTATE_NAME = "ARG_TYPE_MigrationState";
	public static final boolean ARG_TYPE_MIGRATIONSTATE_SENDS_EVENTS     = false;
	public static final Class ARG_TYPE_MIGRATIONSTATE_JAVA_DATA_TYPE     = java.lang.String.class;
	public static final String ARG_TYPE_MIGRATIONSTATE_UPNP_DATA_TYPE    = "string";
	public static final String [] ARG_TYPE_MIGRATIONSTATE_ALLOWED_VALUES = null;
	public static final Object ARG_TYPE_MIGRATIONSTATE_DEFAULT_VALUE     = null;
	public static final Number ARG_TYPE_MIGRATIONSTATE_MINIMUM = null;
	public static final Number ARG_TYPE_MIGRATIONSTATE_MAXIMUM = null;
	public static final Number ARG_TYPE_MIGRATIONSTATE_STEP = null;

	public static UPnPStateVariable [] createUPnPStateVariables() {
		return new UPnPStateVariable [] {
			new UPnPGenStateVariable(ARG_TYPE_BUNDLEURL_NAME,
			ARG_TYPE_BUNDLEURL_SENDS_EVENTS,
			ARG_TYPE_BUNDLEURL_JAVA_DATA_TYPE,
			ARG_TYPE_BUNDLEURL_UPNP_DATA_TYPE,
			ARG_TYPE_BUNDLEURL_ALLOWED_VALUES,
			ARG_TYPE_BUNDLEURL_DEFAULT_VALUE,
			ARG_TYPE_BUNDLEURL_MINIMUM,
			ARG_TYPE_BUNDLEURL_MAXIMUM,
			ARG_TYPE_BUNDLEURL_STEP),
			new UPnPGenStateVariable(ARG_TYPE_MIGRATIONSTATE_NAME,
			ARG_TYPE_MIGRATIONSTATE_SENDS_EVENTS,
			ARG_TYPE_MIGRATIONSTATE_JAVA_DATA_TYPE,
			ARG_TYPE_MIGRATIONSTATE_UPNP_DATA_TYPE,
			ARG_TYPE_MIGRATIONSTATE_ALLOWED_VALUES,
			ARG_TYPE_MIGRATIONSTATE_DEFAULT_VALUE,
			ARG_TYPE_MIGRATIONSTATE_MINIMUM,
			ARG_TYPE_MIGRATIONSTATE_MAXIMUM,
			ARG_TYPE_MIGRATIONSTATE_STEP)
		};
	}
}
