/**
 * LocalManagerService.java
 * 
 * generated by France Telecom UPnP Generator
 * 
 */

package com.orange.homenap.localmanager.upnp.services;


import com.orange.homenap.api.ILocalManagerService;
import org.osgi.service.upnp.*;
import java.util.Hashtable;
import java.util.HashMap;
import java.util.Map;
import java.util.Dictionary;

import org.osgi.framework.*;
import com.orange.homenap.localmanager.upnp.holders.*;

    /**
	* This is the class representing a LocalManagerService
	*/
public class LocalManagerService implements ILocalManagerService {
	UPnPService service;
	Map map=new HashMap();
	BundleContext context;
	ServiceRegistration registration;
	LocalManagerServiceSkel skel;
	String deviceId;

	public LocalManagerService(UPnPService service,String deviceId,BundleContext context) {
		this.context=context;
		this.service=service;
		this.deviceId=deviceId;
	}
	public UPnPService getGenericService() {
		return service;
	}
	/**
	* OSGI Stub for UPnP action ActionsToTake
	*/
	public void actionsToTake(java.lang.String actions) throws Exception {
		Dictionary dict = null;
		dict = new Hashtable(1);
		dict.put(new String("Actions"), actions);
		Hashtable result=null;
		try {
		result=(Hashtable)service.getAction("ActionsToTake").invoke(dict);
		}
		catch (NullPointerException ex) {
			throw new UPnPGenException("The action is not availaible on the device: It may be an optional action...");
		}
	}
}
