/**
 * LocalManagerActionHandler.java
 * 
 * generated by France Telecom UPnP Generator
 * 
 */

package com.orange.homenap.localmanager.upnp.services;


import com.orange.homenap.api.ILocalManagerService;

import java.util.Dictionary;

/**
	* null
	*/
public class LocalManagerActionHandler {
	public static Dictionary actionsToTake_invoke(Dictionary args, ILocalManagerService service) throws Exception {
		Dictionary resultDict = null;
		java.lang.String value0=null;
		try {
			value0=(java.lang.String)args.get("Actions");
		}
		catch (Exception ex) {
			ex.printStackTrace();
		}
		service.actionsToTake(value0);
		return resultDict;
	}

}
