/*
 * --------------------------------------------------------
 *  Module Name : local-manager-upnp
 *  Version : 0.1-SNAPSHOT
 *
 *  Software Name : HomeNap
 *  Version : 0.1-SNAPSHOT
 *
 *  Copyright © 28/06/2012 – 28/06/2012 France Télécom
 *  This software is distributed under the Apache 2.0 license,
 *  the text of which is available at http://www.apache.org/licenses/LICENSE-2.0.html
 *  or see the "LICENSE-2.0.txt" file for more details.
 *
 * --------------------------------------------------------
 *  File Name   : DeployerActionHandler.java
 *
 *  Created     : 28/06/2012
 *  Author(s)   : Remi Druilhe
 *
 *  Description :
 *
 * --------------------------------------------------------
 */

/**
 * DeployerActionHandler.java
 * 
 * generated by France Telecom UPnP Generator
 * 
 */

package com.orange.homenap.localmanager.upnp.services;


import com.orange.homenap.api.IDeployerService;

import java.util.Dictionary;

/**
	* null
	*/
public class DeployerActionHandler {
	public static Dictionary start_invoke(Dictionary args, IDeployerService service) throws Exception {
		Dictionary resultDict = null;
		java.lang.String value0=null;
		try {
			value0=(java.lang.String)args.get("BundleUrl");
		}
		catch (Exception ex) {
			ex.printStackTrace();
		}
		java.lang.String value1=null;
		try {
			value1=(java.lang.String)args.get("MigrationState");
		}
		catch (Exception ex) {
			ex.printStackTrace();
		}
		service.start(value0,value1);
		return resultDict;
	}

}
