/**
 * GlobalCoordinatorIconsProperties.java
 * 
 * generated by France Telecom UPnP Generator
 * 
 */

package com.orange.homenap.globalcoordinator.upnp.devices;


import org.osgi.service.upnp.*;
import com.orange.homenap.globalcoordinator.upnp.holders.*;

    /**
	* null
	*/
public class GlobalCoordinatorIconsProperties {
}
