/**
 * GlobalCoordinatorActionHandler.java
 * 
 * generated by France Telecom UPnP Generator
 * 
 */

package com.orange.homenap.globalcoordinator.upnp.services;


import com.orange.homenap.api.IGlobalCoordinatorService;

import java.util.Hashtable;
import java.util.Dictionary;

/**
	* null
	*/
public class GlobalCoordinatorActionHandler {
	public static Dictionary stopService_invoke(Dictionary args, IGlobalCoordinatorService service) throws Exception {
		Dictionary resultDict = null;
		String value0=null;
		try {
			value0=(String)args.get("ServiceId");
		}
		catch (Exception ex) {
			ex.printStackTrace();
		}
		service.stopService(value0);
		return resultDict;
	}

	public static Dictionary register_invoke(Dictionary args, com.orange.homenap.api.IGlobalCoordinatorService service) throws Exception {
		Dictionary resultDict = null;
		String value0=null;
		try {
			value0=(String)args.get("DeviceInfo");
		}
		catch (Exception ex) {
			ex.printStackTrace();
		}
		boolean returnValue = 		service.register(value0);
		resultDict = new Hashtable(1);
		resultDict.put(new String("Success"), new Boolean(returnValue));
		return resultDict;
	}

	public static Dictionary startService_invoke(Dictionary args, com.orange.homenap.api.IGlobalCoordinatorService service) throws Exception {
		Dictionary resultDict = null;
		String value0=null;
		try {
			value0=(String)args.get("ServiceInfo");
		}
		catch (Exception ex) {
			ex.printStackTrace();
		}
		String value1=null;
		try {
			value1=(String)args.get("DeviceId");
		}
		catch (Exception ex) {
			ex.printStackTrace();
		}
		service.startService(value0,value1);
		return resultDict;
	}

	public static Dictionary unRegister_invoke(Dictionary args, com.orange.homenap.api.IGlobalCoordinatorService service) throws Exception {
		Dictionary resultDict = null;
		String value0=null;
		try {
			value0=(String)args.get("DeviceId");
		}
		catch (Exception ex) {
			ex.printStackTrace();
		}
		boolean returnValue = 		service.unRegister(value0);
		resultDict = new Hashtable(1);
		resultDict.put(new String("Success"), new Boolean(returnValue));
		return resultDict;
	}

}
