/*
 * --------------------------------------------------------
 *  Module Name : global-coordinator-upnp
 *  Version : 0.1-SNAPSHOT
 *
 *  Software Name : HomeNap
 *  Version : 0.1-SNAPSHOT
 *
 *  Copyright © 28/06/2012 – 28/06/2012 France Télécom
 *  This software is distributed under the Apache 2.0 license,
 *  the text of which is available at http://www.apache.org/licenses/LICENSE-2.0.html
 *  or see the "LICENSE-2.0.txt" file for more details.
 *
 * --------------------------------------------------------
 *  File Name   : GlobalCoordinatorActionHandler.java
 *
 *  Created     : 28/06/2012
 *  Author(s)   : Remi Druilhe
 *
 *  Description :
 *
 *  generated by France Telecom UPnP Generator
 *
 * --------------------------------------------------------
 */

package com.orange.homenap.globalcoordinator.upnp.services;


import java.util.Hashtable;
import java.util.Dictionary;

import com.orange.homenap.api.IGlobalCoordinatorService;

    /**
	* null
	*/
public class GlobalCoordinatorActionHandler {
	public static Dictionary updateServicesState_invoke(Dictionary args, IGlobalCoordinatorService service) throws Exception {
		Dictionary resultDict = null;
		java.lang.String value0=null;
		try {
			value0=(java.lang.String)args.get("DeviceId");
		}
		catch (Exception ex) {
			ex.printStackTrace();
		}
		java.lang.String value1=null;
		try {
			value1=(java.lang.String)args.get("ServicesState");
		}
		catch (Exception ex) {
			ex.printStackTrace();
		}
		service.updateServicesState(value0,value1);
		return resultDict;
	}

	public static Dictionary updateDeviceState_invoke(Dictionary args, IGlobalCoordinatorService service) throws Exception {
		Dictionary resultDict = null;
		java.lang.String value0=null;
		try {
			value0=(java.lang.String)args.get("DeviceId");
		}
		catch (Exception ex) {
			ex.printStackTrace();
		}
		java.lang.String value1=null;
		try {
			value1=(java.lang.String)args.get("State");
		}
		catch (Exception ex) {
			ex.printStackTrace();
		}
		service.updateDeviceState(value0,value1);
		return resultDict;
	}

	public static Dictionary register_invoke(Dictionary args, IGlobalCoordinatorService service) throws Exception {
		Dictionary resultDict = null;
		java.lang.String value0=null;
		try {
			value0=(java.lang.String)args.get("DeviceInfo");
		}
		catch (Exception ex) {
			ex.printStackTrace();
		}
		boolean returnValue = 		service.register(value0);
		resultDict = new Hashtable(1);
		resultDict.put(new String("Success"), new java.lang.Boolean(returnValue));
		return resultDict;
	}

	public static Dictionary unRegister_invoke(Dictionary args, IGlobalCoordinatorService service) throws Exception {
		Dictionary resultDict = null;
		java.lang.String value0=null;
		try {
			value0=(java.lang.String)args.get("DeviceId");
		}
		catch (Exception ex) {
			ex.printStackTrace();
		}
		boolean returnValue = 		service.unRegister(value0);
		resultDict = new Hashtable(1);
		resultDict.put(new String("Success"), new java.lang.Boolean(returnValue));
		return resultDict;
	}

}
