/**
 * IDeployerService.java
 * 
 * generated by France Telecom UPnP Generator
 * 
 */

package com.orange.homenap.api;



    /**
	* This is the interface for a DeployerService
	*/
public interface IDeployerService {
	/**
	* Interface declaration for UPnP action: Start
	*/
	public void start(java.lang.String bundleUrl, java.lang.String migrationState) throws Exception;
}
