/*--------------------------------------------------------
* Module Name : API
* Version : 0.1-SNAPSHOT
*
* Software Name : HomeNap
* Version : 0.1-SNAPSHOT
*
* Copyright © 28/06/2012 – 28/06/2012 France Télécom
* This software is distributed under the Apache 2.0 license,
* the text of which is available at http://www.apache.org/licenses/LICENSE-2.0.html
* or see the "LICENSE-2.0.txt" file for more details.
*
*--------------------------------------------------------
* File Name   : IGlobalCoordinatorService.java
*
* Created     : 28/06/2012
* Author(s)   : Remi Druilhe
*
* Description :
*
* generated by France Telecom UPnP Generator
*
*--------------------------------------------------------
*/

package com.olnc.made.homenap.api;

    /**
	* This is the interface for a GlobalCoordinatorService
	*/
public interface IGlobalCoordinatorService {
	/**
	* Interface declaration for UPnP action: UpdateServicesState
	*/
	public void updateServicesState(java.lang.String deviceId, java.lang.String servicesState) throws Exception;
	/**
	* Interface declaration for UPnP action: UpdateDeviceState
	*/
	public void updateDeviceState(java.lang.String deviceId, java.lang.String state) throws Exception;
	/**
	* Interface declaration for UPnP action: Register
	*/
	public boolean register(java.lang.String deviceInfo) throws Exception;
	/**
	* Interface declaration for UPnP action: UnRegister
	*/
	public boolean unRegister(java.lang.String deviceId) throws Exception;
}
