/*--------------------------------------------------------
* Module Name : API
* Version : 0.1-SNAPSHOT
*
* Software Name : HomeNap
* Version : 0.1-SNAPSHOT
*
* Copyright © 28/06/2012 – 28/06/2012 France Télécom
* This software is distributed under the Apache 2.0 license,
* the text of which is available at http://www.apache.org/licenses/LICENSE-2.0.html
* or see the "LICENSE-2.0.txt" file for more details.
*
*--------------------------------------------------------
* File Name   : ILocalManagerService.java
*
* Created     : 28/06/2012
* Author(s)   : Remi Druilhe
*
* Description :
*
* generated by France Telecom UPnP Generator
*
*--------------------------------------------------------
*/

package com.olnc.made.homenap.api;



    /**
	* This is the interface for a LocalManagerService
	*/
public interface ILocalManagerService {
	/**
	* Interface declaration for UPnP action: MigrateService
	*/
	public void migrateService(java.lang.String serviceId, java.lang.String toDeviceId, java.lang.String wakeUpAddress) throws Exception;
}
